# Generated by Django 4.2 on 2024-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basementapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='Room_types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
