# Generated by Django 4.2 on 2024-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basementapp', '0003_mastermodel_estimated_walk_mastermodel_lavatory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastermodel',
            old_name='ress_name',
            new_name='Resident_name',
        ),
    ]
