# Generated by Django 4.2 on 2024-01-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basementapp', '0005_landlord_alter_mastermodel_estimated_walk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='landlord',
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='commune_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='double_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='single_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
