# Generated by Django 4.2 on 2024-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basementapp', '0006_delete_landlord_mastermodel_commune_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='vacant_rooms',
            field=models.SmallIntegerField(default=0),
        ),
    ]
