# Generated by Django 4.2 on 2024-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basementapp', '0007_mastermodel_vacant_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='base_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
