# Generated by Django 4.2 on 2024-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basementapp', '0008_mastermodel_base_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mastermodel',
            name='base_title',
        ),
    ]
